#连接数据库的四大参数
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_crowd?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #指定连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
    #显示sql语句
  jpa:
    show-sql: true
    #正向工程
    hibernate:
      ddl-auto: update
